article/models.py
from app import db


class Article(db.Model):
    __table__ = db.metadata.tables['article']

user/models.py
from app import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    __table__ = db.metadata.tables['user']

app/__init__.py
import os
from pathlib import Path

from dotenv import load_dotenv
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import DeclarativeBase
from flask_login import LoginManager

login_manager = LoginManager()


class Base(DeclarativeBase):
    pass


db = SQLAlchemy(model_class=Base)


# 加载环境变量
load_dotenv()


def create_app():
    """工厂函数"""
    app = Flask(__name__, template_folder='../templates', static_folder='../static')

    app.config['DEBUG'] = os.environ.get('DEBUG')
    app.config['TESTING'] = os.environ.get('TESTING')
    app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY')
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('SQLALCHEMY_DATABASE_URI')
    app.config['UPLOAD_FOLDER'] = '../upload'

    # 注册Flask-SQLAlchemy
    db.init_app(app)
    with app.app_context():
        # 根据数据库表格反射获取用户模型类
        db.reflect()

    # 注册Flask-Login
    from user.models import User

    @login_manager.user_loader
    def load_user(user_id):
        return db.session.execute(
            db.select(User).filter_by(id=user_id)
        ).scalar()
    login_manager.login_view = 'user.login'
    login_manager.login_message = '请先登录'
    login_manager.init_app(app)

    # 注册蓝图
    init_bp(app)

    # 测试路由
    @app.route('/hello')
    def hello_world():
        return 'Hello, World!'

    # 添加跟路由
    app.add_url_rule('/', 'article.index')

    return app


def init_bp(app):
    """注册路由"""
    from user.views import user_bp
    from article.views import article_bp

    app.register_blueprint(user_bp, url_prefix='/user')
    app.register_blueprint(article_bp, url_prefix='/article')


# 项目根路径
ROOT_PATH = Path(__file__).parent.parent
# 图片上传路径
IMAGE_ROOT = os.path.join(ROOT_PATH, 'upload')

if not os.path.exists(IMAGE_ROOT):
    os.makedirs(IMAGE_ROOT)

article/views.py
import os.path
import uuid

from flask import (
    Blueprint, request, abort, render_template, redirect, url_for, flash, send_from_directory, current_app
)
from http import HTTPStatus
from flask_login import login_required, current_user

from app import db, IMAGE_ROOT
from article.models import Article

from utils.tools import compress_image

article_bp = Blueprint('article', __name__, url_prefix='article')

MAX_IMAGE_SIZE = 3 * 1024 * 1024  # 图片大小最大为3MB
IMAGE_COMPRESS_THRESHOLD = 1 * 1024 * 1024  # 图片大小超过1MB时对图片进行压缩


def get_article(article_id, check_auth=True):
    """根据文章ID获取文章"""
    article = db.session.execute(
        db.select(Article).filter(Article.id == article_id)
    ).scalar()

    if article is None:
        abort(HTTPStatus.NOT_FOUND)

    if check_auth and article.user_id != current_user.id:
        abort(HTTPStatus.NOT_FOUND)

    return article


@article_bp.route('/')
def index():
    """主页"""
    article_list = db.session.execute(
        db.select(Article).order_by(Article.created_at.desc())
    ).scalars()
    return render_template('article/index.html', article_list=article_list)


@article_bp.route('/<int:article_id>')
def detail(article_id):
    """文章详情"""
    article = get_article(article_id, check_auth=False)
    return render_template('article/detail.html', article=article)


@article_bp.route('/add', methods=('GET', 'POST'))
@login_required
def add():
    """新增文章"""
    error = ''
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        if not title:
            error = '请输入文章标题'

        if not error:
            article = Article(title=title, content=content, user_id=current_user.id)
            db.session.add(article)
            db.session.commit()
            return redirect(url_for('article.index'))

    if error:
        flash(error)

    return render_template('article/add.html')


@article_bp.route('/update/<int:article_id>', methods=('GET', 'POST'))
@login_required
def update(article_id):
    """修改文章"""
    error = ''
    article = get_article(article_id)
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']

        if not title:
            error = '请输入文章标题'

        if not error:
            article.title = title
            article.content = content
            db.session.commit()

            return redirect(url_for('article.detail', article_id=article_id))

    if error:
        flash(error)

    return render_template('article/update.html', article=article)


@article_bp.route('/delete/<int:article_id>', methods=('POST',))
@login_required
def delete(article_id):
    """删除文章"""
    # TODO: 待删除相关图片
    article = get_article(article_id)
    db.session.delete(article)
    db.session.commit()
    return redirect(url_for('article.index'))


@article_bp.route('/upload', methods=('GET', 'POST'))
@login_required
def upload():
    """图片上传接口"""
    error = ''
    filename = ''
    if request.method == 'POST':
        if 'file' not in request.files or not request.files['file'].filename:
            error = '未选择图片'
        else:
            file = request.files['file']

            # 验证实际文件大小，注意这会消耗文件流
            file.seek(0, os.SEEK_END)
            file_size = file.tell()
            file.seek(0)  # 重置文件指针

            if file_size > MAX_IMAGE_SIZE:
                error = '图片过大'
            else:
                suffix = file.filename.rsplit('.', 1)[1].lower()
                if suffix in ['jpg', 'jpeg', 'png']:
                    filename = str(uuid.uuid4()) + '.' + suffix
                    file_path = os.path.join(IMAGE_ROOT, filename)
                    file.save(file_path)

                    # 压缩图片
                    if file_size > IMAGE_COMPRESS_THRESHOLD:
                        compress_image(file_path)
                else:
                    error = '图片格式错误'

    if error:
        flash(error)

    return render_template(
        'article/upload.html', filename=url_for('article.uploaded_file', filename=filename)
    )


@article_bp.route('/upload/<filename>', methods=('GET', 'POST'))
def uploaded_file(filename):
    """图片获取接口"""
    return send_from_directory(current_app.config['UPLOAD_FOLDER'], filename)

main.py
from app import create_app

app = create_app()

if __name__ == '__main__':
    app.run(port=9999)

user/views.py
from flask import (
    Blueprint, request, abort, render_template, redirect, url_for, flash
)
from http import HTTPStatus
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, current_user, logout_user

from app import db
from .models import User

user_bp = Blueprint('user', __name__, url_prefix='user')


@user_bp.route('/register', methods=('GET', 'POST'))
def register():
    """用户注册"""
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        re_password = request.form['re_password']
        email = request.form['email']
        nickname = request.form['nickname']
        if password != re_password:
            abort(HTTPStatus.BAD_REQUEST)
        hash_password = generate_password_hash(password)
        user = User(username=username, password=hash_password, email=email, nickname=nickname)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('user.login'))

    return render_template('user/register.html')


@user_bp.route('/login', methods=('GET', 'POST'))
def login():
    """用户登录"""
    error = None
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = db.session.execute(
            db.select(User).filter(User.username == username)
        ).scalar()
        if user is None or not check_password_hash(user.password, password):
            error = '用户名或密码错误'
        else:
            login_user(user)
            return redirect('/')

    if error is not None:
        flash(error, 'danger')
    return render_template('user/login.html')


@user_bp.route('/logout', methods=('GET', 'POST'))
@login_required
def logout():
    logout_user()
    return redirect(url_for('user.login'))


@user_bp.route('/profile')
@login_required
def profile():
    return render_template('user/profile.html')

templates/article/add.html
{% extends 'base.html' %}

{% block title %}新增文章{% endblock %}

{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='toast-ui-editor-3.2.2/css/toastui-editor.min.css') }}"/>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <h2>新增文章</h2>
            <form method="post">
                <div class="mb-3">
                    <label for="title" class="form-label">标题：</label>
                    <input type="text" class="form-control" id="title" placeholder="请输入文章标题" name="title"
                           required>
                </div>
                <div class="mb-3">
                    <label for="editor" class="form-label">正文：</label>

                    <!-- 用于生成Markdown编辑器的容器 -->
                    <div id="editor"></div>
                </div>
                <div>
                    <button type="button" class="btn btn-primary" onclick="add()">保存</button>
                    <a href="{{ url_for('article.upload') }}" target="_blank" class="btn btn-secondary">上传图片</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{{ url_for('static', filename='toast-ui-editor-3.2.2/js/toastui-editor-all.min.js') }}"></script>
<script>
    const editor = new toastui.Editor({
        el: document.querySelector('#editor'),
        previewStyle: 'vertical',
        height: '500px'
    });


    // 使用fetch API发送POST请求
    function add() {
        const formData = new FormData();

        // 向FormData对象添加数据
        let content = editor.getMarkdown()  // 从toastui的editor中获取Markdown内容
        let title = document.getElementById('title').value
        formData.append('title', title);
        formData.append('content', content);

        // console.log(title)
        // console.log(content)

        // 向后端发送post请求新增数据
        fetch('{{ url_for("article.add") }}', {
            method: 'POST',
            body: formData
        })
            .then(response => {
                // 处理响应
                if (!response.ok) {
                    throw new Error('Network response was not ok ' + response.statusText);
                }
                // console.log(response)
                window.location.href = '/';
            })
            .then(data => {
                console.log('Success:', data);
            })
            .catch(error => {
                console.error('Error:', error);
            });
    }
</script>
{% endblock %}

templates/article/detail.html
{% extends 'base.html' %}

{% block title %}{{ article.title | truncate(8) }}{% endblock %}

{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='toast-ui-editor-3.2.2/css/toastui-editor.min.css') }}"/>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-4">
        <div class="col-lg-8">
            <h2>{{ article.title }}</h2>
            <textarea id="content" class="d-none">{{ article.content }}</textarea>

            <!-- 用于展示渲染后的Markdown文本 -->
            <div id="viewer"></div>

            <!-- 仅适用于该文章作者的操作 -->
            {% if current_user and article.user_id == current_user.id %}
            <div>
                <a href="{{ url_for('article.update', article_id=article.id) }}" class="btn btn-primary">
                    修改
                </a>
                <form action="{{ url_for('article.delete', article_id=article.id) }}" method="post"
                      style="display: inline-block">
                    <button type="submit" class="btn btn-danger">删除</button>
                </form>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{{ url_for('static', filename='toast-ui-editor-3.2.2/js/toastui-editor-all.min.js') }}"></script>
<script>
    let content = document.getElementById('content').value
    console.log(content)
    const viewer = toastui.Editor.factory({
        el: document.querySelector('#viewer'),
        viewer: true,
        initialValue: content
    });
</script>
{% endblock %}

templates/article/index.html
{% extends 'base.html' %}

{% block title %}首页{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-4">
        <div class="col-lg-8">
            <div class="d-flex">
                <h2>文章列表</h2>
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('article.add') }}"
                   class="btn btn-primary d-inline-block ms-auto align-self-center">
                    新增
                </a>
                {% endif %}
            </div>
            <ul class="list-group list-group-flush">
                {% for article in article_list %}
                <li class="list-group-item d-flex px-0">
                    <a href="{{ url_for('article.detail', article_id=article.id) }}"
                       class="link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                        {{ article.title }}
                    </a>
                    {% if current_user.is_authenticated and current_user.id == article.user_id %}
                    <a href="{{ url_for('article.update', article_id=article.id) }}"
                       class="btn btn-primary btn-sm d-inline-block ms-auto align-self-center">
                        修改
                    </a>
                    <form method="post" action="{{ url_for('article.delete', article_id=article.id) }}"
                          class="d-inline-block ps-2">
                        <button type="submit" class="btn btn-danger btn-sm">删除</button>
                    </form>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/article/update.html
{% extends 'base.html' %}

{% block title %}修改文章{% endblock %}

{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='toast-ui-editor-3.2.2/css/toastui-editor.min.css') }}"/>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <h2>修改文章</h2>
            <form method="post">
                <div class="mb-3">
                    <label for="title" class="form-label">标题：</label>
                    <input type="text" class="form-control" id="title" placeholder="请输入文章标题" name="title"
                           value="{{ request.form.title or article.title }}" required>
                </div>
                <div class="mb-3">
                    <label for="editor" class="form-label">正文：</label>
                    <!-- 用于存放从后端获取到的文章正文 -->
                    <textarea id="content" class="d-none">{{ request.form.content or article.content }}</textarea>

                    <!-- 用于生成Markdown编辑器的容器 -->
                    <div id="editor"></div>
                </div>
                <div>
                    <button type="button" class="btn btn-primary" onclick="update()">保存</button>
                    <a href="{{ url_for('article.upload') }}" target="_blank" class="btn btn-secondary">上传图片</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{{ url_for('static', filename='toast-ui-editor-3.2.2/js/toastui-editor-all.min.js') }}"></script>
<script>
    // 获取修改前的文章正文
    let content = document.getElementById('content').value

    // 初始化toastui的Markdown编辑器
    const editor = new toastui.Editor({
        el: document.querySelector('#editor'),
        previewStyle: 'vertical',
        height: '500px',
        initialValue: content
    });


    // 使用fetch API发送POST请求
    function update() {
        const formData = new FormData();

        // 向FormData对象添加数据
        let content = editor.getMarkdown()  // 从toastui的editor中获取Markdown内容
        let title = document.getElementById('title').value
        formData.append('title', title);
        formData.append('content', content);

        // console.log(title)
        // console.log(content)

        // 向后端发送post请求新增数据
        fetch('{{ url_for("article.update", article_id=article.id) }}', {
            method: 'POST',
            body: formData
        })
            .then(response => {
                // 处理响应
                if (!response.ok) {
                    throw new Error('Network response was not ok ' + response.statusText);
                }
                // console.log(response)
                window.location.href = '{{ url_for("article.detail", article_id=article.id) }}';
            })
            .then(data => {
                console.log('Success:', data);
            })
            .catch(error => {
                console.error('Error:', error);
            });
    }
</script>
{% endblock %}

templates/article/upload.html
{% extends 'base.html' %}

{% block title %}上传图片{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-4">
        <div class="col-lg-8">
            <h2>图片上传</h2>
            <p class="text-secondary">图片最大3MB，格式仅支持：.jpg .jpeg .png</p>
            <form method="post" enctype="multipart/form-data">
                <input class="form-control" type="file" id="formFile" name="file">
                <button type="submit" class="btn btn-primary mt-3">提交</button>
            </form>
            {% if filename != '' and filename != '/article/upload/' %}
            <p>上传成功！</p>
            <p>图片路径：<span class="text-secondary">{{ filename }}</span></p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}-AYC</title>
    <!-- 引入Bootstrap 5的CSS文件 -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap-5.3.3/css/bootstrap.min.css') }}">
    <!-- 引入Bootstrap 5的图标CSS -->
    <link rel="stylesheet"
          href="{{ url_for('static', filename='bootstrap-icons-1.11.3/font/bootstrap-icons.min.css') }}">
    {% block style %}{% endblock %}
</head>
<body>
<!-- 公共导航 -->
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
        <a class="navbar-brand fw-bold" href="/">AYC</a>
        <div class="nav d-flex">
            {% if current_user.is_authenticated %}
            <a href="#" class="nav-link d-inline-block align-self-center text-primary">{{ current_user.username }}</a>
            <a href="{{ url_for('user.logout') }}"
               class="nav-link d-inline-block align-self-center text-primary">注销</a>
            {% else %}
            <a href="{{ url_for('user.login') }}"
               class="nav-link d-inline-block align-self-center text-primary">登录</a>
            <a href="{{ url_for('user.register') }}"
               class="nav-link d-inline-block align-self-center text-primary">注册</a>
            {% endif %}
        </div>
    </div>
</nav>

<!-- 消息闪现 -->
<div class="container">
    {% for msg in get_flashed_messages() %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ msg }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>

<!-- 页面主体 -->
{% block content %}{% endblock %}

<!-- 引入Bootstrap 5的图标CSS -->
<script src="{{ url_for('static', filename='bootstrap-5.3.3/js/bootstrap.bundle.min.js') }}"></script>
<!-- 页面脚本 -->
{% block script %}{% endblock %}
</body>
</html>

templates/user/login.html
{% extends 'base.html' %}

{% block title %}登录{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-4">
        <div class="col-lg-6">
            <div class="mb-4">
                <h2>登录</h2>
            </div>
            <form method="post">
                <div class="row mb-3">
                    <label for="username" class="col-sm-2 col-form-label">用户名：</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="username" name="username" required>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="password" class="col-sm-2 col-form-label">密码：</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">登录</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/user/profile.html
{% extends 'base.html' %}

{% block title %}个人中心{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-4">
        <div class="col-lg-6">
            <div class="mb-4">
                <h2>个人中心</h2>
            </div>
            <form method="post">
                <div class="row mb-3">
                    <label for="username" class="col-sm-2 col-form-label">用户名：</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="username" name="username"
                        value="{{ current_user.username }}" disabled readonly>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="nickname" class="col-sm-2 col-form-label">昵称：</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="nickname" name="nickname"
                        value="{{ current_user.nickname }}" disabled readonly>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="email" class="col-sm-2 col-form-label">邮箱：</label>
                    <div class="col-sm-10">
                        <input type="email" class="form-control" id="email" name="email"
                        value="{{ current_user.email }}" disabled readonly>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/user/register.html
{% extends 'base.html' %}

{% block title %}注册{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-4">
        <div class="col-lg-6">
            <div class="mb-4">
                <h2>注册</h2>
            </div>
            <form method="post">
                <div class="row mb-3">
                    <label for="username" class="col-sm-2 col-form-label">用户名：</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="username" name="username" required>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="nickname" class="col-sm-2 col-form-label">昵称：</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="nickname" name="nickname">
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="email" class="col-sm-2 col-form-label">邮箱：</label>
                    <div class="col-sm-10">
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="password" class="col-sm-2 col-form-label">密码：</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="rePassword" class="col-sm-2 col-form-label">确认密码：</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" id="rePassword" name="re_password" required>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">注册</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}